name: Audit
on:
  schedule:
    - cron: 0 12 * * 1
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installing dependencies 
        run: npm ci 

      - name: Run NPM Audit 
        run: npm run audit 

      - name: Check for dependencies updates 
        # Only to report the result for now 
        continue-on-error: true
        run: npm outdated

      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif